### ISSUE TITLE
AttributeError: 'AtlasView' object has no attribute 'iterkeys'

### ISSUE THREAD

**Issue by mr-september** [bagrow/portraits#1]
Am I at the right place to try and generate the Network Portraits from the Network Portrait Divergence paper/github?
```
python B_matrix.py /media/Python/SV4VSOutputs/GRNBoost2/GRN_DE_query_0.edgelist /media/Python/SV4VSOutputs/GRNBoost2/query_0_portrait.txt
```

```
AttributeError: 'AtlasView' object has no attribute 'iterkeys'
```

Is this just because of the changes in dependencies over the ~8 years?

**Comment by bagrow** [comment]
NetworkX has changed a lot, but this might also be a Python 2 vs. 3 issue. I will look into it.

**Comment by bagrow** [comment]
I think it's fixed. Code is now Python 3.x. Thanks.
